;/*FB_PKG_DELIM*/

__d("oz-player/shims/www/OzStreamsWWW",["cr:927622","cr:927623"],(function(a,b,c,d,e,f,g){"use strict";c=Boolean(b("cr:927622"));d=Boolean(b("cr:927623"));e=b("cr:927622")?b("cr:927622").ReadableStream:a.ReadableStream;f=b("cr:927623")?b("cr:927623").WritableStream:a.WritableStream;g.OzReadableStream=e;g.OzReadableStreamIsPolyfilled=c;g.OzWritableStream=f;g.OzWritableStreamIsPolyfilled=d}),98);
__d("oz-player/shims/OzStreams",["oz-player/shims/www/OzStreamsWWW"],(function(a,b,c,d,e,f,g){"use strict";g.OzReadableStream=d("oz-player/shims/www/OzStreamsWWW").OzReadableStream,g.OzReadableStreamIsPolyfilled=d("oz-player/shims/www/OzStreamsWWW").OzReadableStreamIsPolyfilled,g.OzWritableStream=d("oz-player/shims/www/OzStreamsWWW").OzWritableStream,g.OzWritableStreamIsPolyfilled=d("oz-player/shims/www/OzStreamsWWW").OzWritableStreamIsPolyfilled}),98);
__d("oz-player/shims/www/ozvariantWWW",["invariant"],(function(a,b,c,d,e,f,g,h){a=h;g["default"]=a}),98);
__d("oz-player/shims/ozvariant",["oz-player/shims/www/ozvariantWWW"],(function(a,b,c,d,e,f,g){g["default"]=c("oz-player/shims/www/ozvariantWWW")}),98);
__d("oz-player/networks/OzHTTPHeaders",["oz-player/shims/ozvariant"],(function(a,b,c,d,e,f,g){"use strict";d=function(){function a(){this.$1=new Map()}var b=a.prototype;b.append=function(a,b){a=a.toLowerCase();var c=this.$1.get(a);c!=null?this.$1.set(a,c+", "+b):this.$1.set(a,b)};b.get=function(a){a=a.toLowerCase();a=this.$1.get(a);return(a=a)!=null?a:null};b.entries=function(){return this.$1.entries()};b.has=function(a){return this.get(a)!==null};return a}();e=a.Headers;f=e&&e.prototype;var h=e&&f&&typeof f.append==="function"&&typeof f.entries==="function"&&typeof f.get==="function"&&typeof f.has==="function"?e:d;function b(a){if(a==null)return null;if(typeof a==="object"&&typeof a.append==="function"&&typeof a.get==="function"&&typeof a.has==="function")if(typeof a.entries==="function")return a;else if(typeof a.forEach==="function"){var b=new h();a.forEach(function(a,c){b.append(c,a)});return b}c("oz-player/shims/ozvariant")(!1,"Malformed Headers object: %s %s",typeof a,String(a));return null}g.OzHTTPHeaders=h;g.maybeConvertHeadersToOzHTTPHeaders=b}),98);
__d("oz-player/shims/www/getOzVTTSourceBufferImplLazyWWW",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";var h=c("JSResourceForInteraction")("OzVTTSourceBufferImpl").__setRef("oz-player/shims/www/getOzVTTSourceBufferImplLazyWWW");function a(){return h.load()}g["default"]=a}),98);
__d("oz-player/utils/arrayBuffer2OzReadableStream",["oz-player/shims/OzStreams"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return new(d("oz-player/shims/OzStreams").OzReadableStream)({start:function(b){var c=new Uint8Array(a);b.enqueue(c);b.close()}})}g["default"]=a}),98);
__d("OzConfigurableRequestImplementation",["MaybeNativePromise","oz-player/networks/OzHTTPHeaders","oz-player/utils/arrayBuffer2OzReadableStream","parseHeaders"],(function(a,b,c,d,e,f,g){"use strict";function h(a){var b=new(d("oz-player/networks/OzHTTPHeaders").OzHTTPHeaders)(),e=c("parseHeaders")(a);Object.keys(e).forEach(function(a){b.append(a,e[a])});return b}function a(a,b){return function(d,e,f){var g={url:d,http:e,options:f,method:"GET",responseType:"arraybuffer"};return new(c("MaybeNativePromise"))(function(d,e){a(g,function(a,e,f){var g=(a=a)!=null?a:new ArrayBuffer(0);a=e!=null?parseInt(e,10):0;e=b.inferResponseStatusIsOk2xx?299:399;f={body:c("oz-player/utils/arrayBuffer2OzReadableStream")(g),headers:h(f),ok:b.inferResponseStatusIsOK?a>=200&&a<=e:!0,status:a,arrayBuffer:function(){return c("MaybeNativePromise").resolve(g)}};d(f)},function(a,b,f){if(a==null||a==="0")e(new TypeError("NetworkError"));else{var g=new ArrayBuffer(0);f={body:c("oz-player/utils/arrayBuffer2OzReadableStream")(g),headers:h(b),ok:!1,status:parseInt(a,10),arrayBuffer:function(){return c("MaybeNativePromise").resolve(g)}};d(f)}})})}}g["default"]=a}),98);